# Generated by Django 5.2.1 on 2025-05-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_nome', models.CharField(default='', max_length=100)),
                ('user_email', models.CharField(default='', primary_key=True, serialize=False)),
                ('user_idade', models.CharField(default=0)),
            ],
        ),
    ]
